apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-skill
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: SecretStore
    name: gcp
  target:
    name: slack-skill
    creationPolicy: Owner
  data:
  - secretKey: slack-skill.yaml
    remoteRef:
      key: slack-skill
